# WORKSPACE
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# 引入 rules_python
http_archive(
    name = "rules_python",
    urls = ["https://github.com/bazelbuild/rules_python/releases/download/0.33.2/rules_python-0.33.2.tar.gz"],
    strip_prefix = "rules_python-0.33.2",
)

load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()

# 其他设置

